image: golang:1.6.4

stages:
  - build
  - release

build:linux:
  stage: build
  before_script:
    - go get github.com/constabulary/gb/...
    - gb vendor restore
  script:
    - gb build
  artifacts:
    name: "musicbot"
    expire_in: "1 week"
    paths:
      - bin/musicbot
      - bin/spotify.sh
      - run.sh
      - whitelist.txt
      - conf.json.example

release:linux:
  stage: release
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-.]+)?$/
  artifacts:
    name: "musicbot"
    paths:
      - bin/musicbot
      - bin/spotify.sh
      - run.sh
      - whitelist.txt
      - conf.json.example

