image: golang:1.6.4

stages:
  - build

build:linux:
  stage: build
  before_script:
    - go get github.com/constabulary/gb/...
    - gb vendor restore
  script:
    - gb build
  artifacts:
    paths:
      - bin/musicbot
