image: golang:1.6.4
stages:
  - build
  - release
build:linux:
  stage: build
  before_script:
    - curl https://glide.sh/get | sh
    - P="$(pwd)"; mkdir -p /go/src/gitlab.transip.us/swiltink; cd /go/src/gitlab.transip.us/swiltink; ln -s $P go-MusicBot; cd go-MusicBot;
    - mkdir -p ~/.ssh/
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_KEY")
    - ssh-keyscan -t rsa gitlab.transip.us >> ~/.ssh/known_hosts
    - git config --global url."git@gitlab.transip.us".insteadOf "https://gitlab.transip.us/"
    - git clone git@gitlab.transip.us:swiltink/go-MusicPlayer.git
    - glide install
  script:
    - cd /go/src/gitlab.transip.us/swiltink/go-MusicBot
    - go build -o MusicBot

release:linux:test:
  stage: release
  only:
    - branches
  except:
    - master@gitlab.transip.us/swiltink/go-MusicBot
  artifacts:
    name: "musicbot"
    expire_in: "1 week"
    paths:
      - MusicBot
      - whitelist.txt
      - conf.json.example

release:linux:
  stage: release
  script:
    - ls
  only:
    - tags
  artifacts:
    name: "musicbot"
    paths:
      - MusicBot
      - whitelist.txt
      - conf.json.example