image: golang:1.6.4
stages:
  - build
  - release
build:linux:
  stage: build
  before_script:
    - curl https://glide.sh/get | sh
    - P="$(pwd)"; mkdir -p /go/src/gitlab.sgttailor.com/Sgt_Tailor; cd /go/src/gitlab.sgttailor.com/Sgt_Tailor; ln -s $P MusicBot; cd MusicBot;
    - glide up
    - glide install
  script:
    - cd /go/src/gitlab.sgttailor.com/Sgt_Tailor/MusicBot
    - go build
  artifacts:
    name: "musicbot"
    expire_in: "1 week"
    paths:
      - MusicBot
      - whitelist.txt
      - conf.json.example

release:linux:
  stage: release
  script:
    - ls
  only:
    - tags
  artifacts:
    name: "musicbot"
    paths:
      - MusicBot
      - whitelist.txt
      - conf.json.example