language: go
go:
- 1.11.x
env:
- GO111MODULE=on
install: true

jobs:
  include:
  - stage: formatting
    script:
    - make fmt
  - script:
    - make deps
    - make lint
  - stage: build
    script:
    - make deps
    - make build
    - mkdir out/archives
    - ls -1 out/binaries | xargs -L 1 -I{}  tar -cf out/archives/{}.tar --transform='flags=r;s|.*\MusicBot.*\(\..*\)|MusicBot\1|' --transform='flags=r;s|dist/||' out/binaries/{} dist/config.json.example
    deploy:
      - provider: releases
        api_key:
          secure: hmEPa5FCvu16GTt9kA1djudi2+gOrvpTarwc1yEruCDR76bn1dKa+KfaunyQL6L78zQPD2NTKI3J8OiEyoO68uOnsuAi+JKeX5a1UsnFvJaUWgmJ6l+NTgUPc++HUl86VeBqnzxuP7g2jUimhAA/LB5d7TCREuFW1Nm2ITqEpFhbRPOImniOZ2B0cxxorwdaMvwQ0QPCVVMTIuUnFzDPw1Xf0RNHa4s3U9JPHAh1N+NHMwXxDS8zaoplSjzyiiHxa9TBE4VdUoSkBMx0VtOK5X6ynItsPlBfG9TW7QuKBtUlW0sHhVkFZCYwU72Lnmlj6SgN2sOl2x1jAHwOT+tBHVgy6TtCwlLKP4H5EH4ptlTSkwBISZvrmEtmR2TW0Gt2y7jjmw2jeVCUS0kBFq+fNnFBzKKQJvwVztHnV3KxMRT1ubW02e6zyHd9wBAEk9VL/Gjgy7+N/o4wt8voB1Cp1qcYpneHDXOuf/MADUUmOyZXF1thtBmF5poZWJaSTXO9sdwdHZyqwfe58mJBK9adJ6Fu63O9opD4ZaG0IpMdlj6tJapUu57zRSa4BRelS8zbPtmWw3xEByF3n9KT4QV/tB8TxfAVt3OF/D/HFSsEzSjYRj7+Z7+lZUfIbRxBPBKwo54HjQj5wyR6FsuqJ7LH2OnMuPFtkWfCfJM2ZHvS8tY=
        file_glob: true
        file:
        - out/archives/*
        on:
          tags: true
        skip_cleanup: true
      - provider: packagecloud
        local-dir: out/packages
        username: svenwiltink
        repository: go-musicbot
        dist: ubuntu/bionic
        token:
          secure: cSNkBddUy+CoJHhFDBeIt/3w0AeqPx0kJ2Z6xrnCcbRY7KjPloHCw7WxOl4EqWw4+zyCL1M2S4EYplKD2xL9SsIM7qQ8FgX2QiA50fVs0QuxzVGw7yML3bU6P/GmPjJ36hNcReGb7Ev388RWZD7141jcowD/AtwiBARynexn/JjHKhcS8G1T819n/jjISt8YLTexJuXNBxDVUAixvG6xZP0SgcmYAE6MPDXYoBJi5jklMVqP3+uhaB6RMJlu4/Fcl0X8ZJ1uhZuAFvKHjAuY5B7aaDaouyP1YU1IQ9QE4Tez0yU0u2oYVR7BR8AOM0sWdujkE/oGlTyvL/myFy93s86hdplBnY3RNEv54apaANmxttaetpYFSS0VluSOIm8FRfaYW1DLBwr5JQaOMTxoDOUG8RghuvvsTN2Dc/gmj32yZ1swSBbevlXFbHmzwcwIYcthRMlKkfZA1BpI07n7bt6NFW75USP6rYWAB+qU/SrAtR2JmuNPShUWiUYsatLwftmGZGZp3SkTupscPwLACzJlbl5aTxDBPqubySqk+TassaNf8pHDTBJnB/RBE9YprlcEBKtwfkrR5CG8VsODzRHZMcZdgwSd+iZMZ3+7JE7aqg6TVVPHHr2AOIzXq3Iif18fMDcAe9uMvdXCMVO+jhp6+4p11UWKwYgrZyKnWaE=
